-- 0048_neighbourhood_coord_provenance_guard.sql
--
-- Coordinate provenance, and a tripwire on linking listings to zones.
--
-- Every neighbourhood coordinate in this table is synthetic. generate_seed.py
-- (lines 94-96) sets each zone to `CITY_COORDS[city] + md5-jitter(±0.02°)` --
-- the city centroid plus noise. There was never a gazetteer. The consequence is
-- that each zone's error equals its real distance from the city centre.
-- Measured against known positions:
--
--     Epe              67.1 km
--     Sangotedo        30.4 km
--     Ajah             20.5 km
--     Victoria Island  11.5 km   (sits on the mainland, near Surulere)
--     Ikoyi            11.2 km
--     Ikeja GRA         7.1 km
--     Lekki Phase 1     0.8 km   } accurate only because they happen to
--     Yaba              1.0 km   } sit near the city centroid
--
-- Nothing is currently harmed by this, because `properties.neighbourhood_id`
-- is NULL on every row, so the join in toju-demo yields nothing. That is also
-- exactly why it is dangerous: backfilling neighbourhood_id -- an obvious,
-- cheap-looking next step -- is the single action that would turn these
-- coordinates into live flood-risk and safety claims shown to buyers.
--
-- So the tripwire is placed on the link, not on the data. A listing may only
-- be attached to a zone whose coordinates a human has actually curated. The
-- gate is the data, not the caller, so it applies to the service role too --
-- a backfill script is precisely what it is guarding against.
--
-- See also: toju-demo now selects only `neighbourhoods(name)`, because the
-- scores and summary on this table are seed_rand output, not measurements.

alter table public.neighbourhoods
  add column if not exists coord_source text,
  add column if not exists coord_verified_at timestamptz;

comment on column public.neighbourhoods.coord_source is
  'Provenance of latitude/longitude. "synthetic_seed" = generated by generate_seed.py as city centroid + jitter and NOT usable. "curated" = checked against a real source by a person, with coord_verified_at set.';

update public.neighbourhoods
   set coord_source = 'synthetic_seed'
 where coord_source is null;

create or replace function public.properties_guard_neighbourhood_link()
returns trigger
language plpgsql
as $$
declare
  v_source text;
  v_name   text;
begin
  if new.neighbourhood_id is null then
    return new;
  end if;
  if tg_op = 'UPDATE' and new.neighbourhood_id is not distinct from old.neighbourhood_id then
    return new;   -- unchanged link on an unrelated update
  end if;

  select coord_source, name into v_source, v_name
  from neighbourhoods where id = new.neighbourhood_id;

  if coalesce(v_source, 'synthetic_seed') <> 'curated' then
    raise exception
      'Cannot link a listing to "%": its coordinates are % and have not been curated. Fix the coordinate and set coord_source = ''curated'' first.',
      coalesce(v_name, new.neighbourhood_id::text), coalesce(v_source, 'unset')
      using errcode = 'raise_exception';
  end if;

  return new;
end;
$$;

drop trigger if exists properties_guard_neighbourhood_link_trg on public.properties;
create trigger properties_guard_neighbourhood_link_trg
  before insert or update on public.properties
  for each row execute function public.properties_guard_neighbourhood_link();

-- Verified behaviour (2026-08-13):
--   link a listing to a synthetic zone  -> blocked, names the zone and the reason
--   unrelated UPDATE on the same row    -> unaffected
--   link after setting coord_source     -> allowed
